apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matchid

labels:
  - pairs:
      app.kubernetes.io/part-of: matchid
    includeSelectors: true

resources:
  - namespace.yaml
  - elasticsearch.statefulset.yaml
  - deces-backend.deployment.yaml
  - deces-backend.service.yaml
  - deces-ui.deployment.yaml
  - deces-ui.service.yaml
  - ingress.yaml
