apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matchid

resources:
  - ../../base
  - es-data-pv.yaml

patches:
  - path: deces-ui.nodeport.yaml
    target:
      kind: Service
      name: deces-ui
  - path: deces-backend.nodeport.yaml
    target:
      kind: Service
      name: deces-backend
  - path: elasticsearch.local-storage.yaml
    target:
      kind: StatefulSet
      name: elasticsearch
