apiVersion: apps/v1
kind: Deployment
metadata:
  name: deces-backend
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        k8s.scaleway.com/pool-name: burst-rwx
      containers:
        - name: deces-backend
          env:
            - name: APP_DNS
              value: dev.deces.matchid.io
            - name: APP_URL
              value: https://dev.deces.matchid.io
          envFrom:
            - secretRef:
                name: deces-backend-secrets
                optional: false
          resources:
            requests:
              cpu: 30m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
